In [ ]:
import numpy as np
np_arr=np.array([1,2,3,4,5])
print(np_arr)
np_arr2=np.array([1,2,3],[4,5,6])
print(np.arr2)

In [3]:
import numpy as np
np_arr=np.zeros(5)
print(np_arr)
np_arr2=np.zeros((3,4))
print(np_arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
import numpy as np
np_arr=np.ones(5)
print(np_arr)
np_arr2=np.ones((3,4))
print(np_arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
import numpy as np
np_arr=np.arange(1,10.5)
np_arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
import numpy as np
np_arr=np.linspace(1,10,15)
np_arr

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [7]:
import numpy as np
np_arr=[[1,2,3],[4,5,6]]
np.ndim(np_arr)


2

In [ ]:
import numpy as np
np_arr = np.array([1, 2, 3, 4])
np_arr = np.reshape(np_arr, (2, 2)) 
print(np_arr)


ValueError: cannot reshape array of size 1 into shape (2,)