In [3]:
import numpy as np

# Correcting the array creation syntax
arr = np.array([[1, 2], [3, 4], [5, 6]])
flatten_arr = arr.flatten()  
print(flatten_arr)

# Correcting the reshape operation
arr1 = np.array([1, 2, 3, 4, 5, 6])
reshape_arr = arr1.reshape(2, 3) 
print(reshape_arr)

# Correcting the reshape operation with valid dimensions
arr2 = np.array([1, 2, 3, 4, 5, 6])
result = np.reshape(arr2, (2, 3))  # Fixed reshape dimensions
print(result)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])
stacked = np.stack((a, b), axis=0)  
print(stacked)



[[1 2 3]
 [4 5 6]]


In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
stacked=np.vstack((a,b))
print(stacked)


[[1 2 3]
 [4 5 6]]


In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
stack=np.hstack((a,b))
print(stack)

[1 2 3 4 5 6]
